// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {connection} from '../models';
import {settings} from '../models';

export function ConnectRDP(arg1:string):Promise<string>;

export function ConnectSSH(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ConnectSerial(arg1:string):Promise<string>;

export function ConnectTelnet(arg1:string,arg2:number,arg3:number):Promise<string>;

export function CreateFolder(arg1:session.Folder):Promise<session.Folder>;

export function CreateSession(arg1:session.Session):Promise<session.Session>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetActiveConnections():Promise<Array<connection.ConnInfo>>;

export function GetConnectionInfo(arg1:string):Promise<connection.ConnInfo>;

export function GetFolders():Promise<Array<session.Folder>>;

export function GetPassword(arg1:string):Promise<string>;

export function GetSession(arg1:string):Promise<session.Session>;

export function GetSessions():Promise<Array<session.Session>>;

export function GetSettings():Promise<settings.Settings>;

export function ListSerialPorts():Promise<Array<string>>;

export function QuickConnectSSH(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveTerminalOutput(arg1:string):Promise<string>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function UpdateFolder(arg1:session.Folder):Promise<void>;

export function UpdateSession(arg1:session.Session):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
