// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectRDP(arg1) {
  return window['go']['main']['App']['ConnectRDP'](arg1);
}

export function ConnectSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3);
}

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function ConnectTelnet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectTelnet'](arg1, arg2, arg3);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetConnectionInfo(arg1) {
  return window['go']['main']['App']['GetConnectionInfo'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function QuickConnectSSH(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['QuickConnectSSH'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SaveTerminalOutput(arg1) {
  return window['go']['main']['App']['SaveTerminalOutput'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function UpdateFolder(arg1) {
  return window['go']['main']['App']['UpdateFolder'](arg1);
}

export function UpdateSession(arg1) {
  return window['go']['main']['App']['UpdateSession'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
